rs1:
  image: mongo:3.2
  volumes:
    - ~/mongo_replset/rs1:/data/db
rs2:
  image: mongo:3.2
  volumes: 
    - ~/mongo_replset/rs2:/data/db



    # version: '2'
    # services:
    #   web:
    #     image: compose/python_app
    #     ports:
    #      - "5000:5000"
    #     volumes:
    #      - .:/code
    #     depends_on:
    #      - redis
    #   redis:
    #     image: redis